
import project.connectionprovider;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/*
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mayur
 */
public class billingcounter extends javax.swing.JFrame {
public int flag=0;
double totals ;
double labss;
double ad;
double fin;
    /**
     * Creates new form billingcounter
     */
    public billingcounter() {
        initComponents();
        jLabel3.setVisible(false);
        jLabel9.setVisible(false);
        jLabel13.setVisible(false);
        jLabel15.setVisible(false);
        jLabel14.setVisible(false);
        jTextField2.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField4.setVisible(false);
        jLabel12.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField10 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Billing Counter");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, -1, -1));

        jLabel2.setBackground(new java.awt.Color(254, 254, 254));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Patient ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, -1, -1));

        jTextField1.setBackground(new java.awt.Color(254, 254, 254));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(1, 1, 1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 169, -1));

        jButton1.setBackground(new java.awt.Color(254, 254, 254));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton1.setForeground(new java.awt.Color(1, 1, 1));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, -1, -1));

        jLabel3.setBackground(new java.awt.Color(225, 1, 1));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Patient ID Does not exist !");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(254, 254, 254));
        jScrollPane1.setForeground(java.awt.Color.white);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(40);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1850, 80));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Bill No.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setText("Patiente Type");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Doctor Charge");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("Lab -:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, -1, -1));

        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(254, 254, 254));
        jCheckBox1.setText("yes ");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 630, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("Lab Charge");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, -1, -1));

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(1, 1, 1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 200, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setText("Admit ??");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 710, -1, -1));

        jCheckBox2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(254, 254, 254));
        jCheckBox2.setText("yes");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 710, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(254, 254, 254));
        jLabel11.setText("Medicine Charge");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setText("Nurse  Charge");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 550, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(254, 254, 254));
        jLabel13.setText("No. of days ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(254, 254, 254));
        jLabel14.setText("Room  Charge");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(254, 254, 254));
        jLabel15.setText("Operation  Charge");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 640, -1, -1));

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(1, 1, 1));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, 200, -1));

        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(1, 1, 1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 530, 200, -1));

        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(1, 1, 1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 350, 200, -1));

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(1, 1, 1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, 200, -1));

        jTextField7.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(1, 1, 1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 620, 200, -1));

        jTextField8.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(1, 1, 1));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 790, 200, -1));

        jTextField9.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(1, 1, 1));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 200, -1));

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(254, 254, 254));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admit patient", "Out Patient", "Lab Checkup", "Operation " }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 200, -1));

        jTextField10.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(1, 1, 1));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 200, -1));

        jButton2.setBackground(new java.awt.Color(254, 254, 254));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save-icon--1.png"))); // NOI18N
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 890, -1, -1));

        jButton3.setBackground(new java.awt.Color(254, 254, 254));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        jButton3.setText("CLOSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 890, -1, -1));

        jButton4.setBackground(new java.awt.Color(254, 254, 254));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton4.setForeground(new java.awt.Color(1, 1, 1));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save-icon--1.png"))); // NOI18N
        jButton4.setText("PRINT ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 750, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 240, 800, 710));

        jButton5.setBackground(new java.awt.Color(254, 254, 254));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton5.setForeground(new java.awt.Color(1, 1, 1));
        jButton5.setText("Total Charge ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 790, -1, -1));

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButton6.setText("RESET");
        jButton6.setToolTipText("");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 750, -1, -1));

        jLabel16.setForeground(new java.awt.Color(1, 1, 1));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/general1 copy.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -10, 1920, 980));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
        {
        jLabel9.setVisible(true);
        jTextField2.setVisible(true);
        }
        else
        {
        jLabel9.setVisible(false);
        jTextField2.setVisible(false);
        }
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
         if(jCheckBox2.isSelected())
        {
        jLabel13.setVisible(true);
        jLabel14.setVisible(true);
        jLabel15.setVisible(true);
        jTextField5.setVisible(true);
        jTextField6.setVisible(true);
        jTextField7.setVisible(true);
        jTextField4.setVisible(true);
        jLabel12.setVisible(true);
        
        }
        else
        {
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField4.setVisible(false);
        jLabel12.setVisible(false);
        
        }
        
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String p_id=jTextField1.getText();
        try {
            Connection con = connectionprovider.getcon();
            Statement st = con.createStatement();
            ResultSet rs=st.executeQuery("select *from patient where patient_id='"+p_id+"'");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            if(!rs.first())
                jLabel3.setVisible(true);
            else{
                jLabel3.setVisible(false);
                jTextField1.setEditable(false);
                flag=1;
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"connection error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if (flag==1)    
        {
            String p_id=jTextField1.getText();
            Integer.parseInt(p_id);
            String bill_no=jTextField9.getText();
            Integer.parseInt(bill_no);
            String p_type =(String)jComboBox1.getSelectedItem();
            String doc_charge=jTextField10.getText();
            Double.parseDouble(doc_charge);
            String medicine_charge=jTextField3.getText();
            Double.parseDouble(medicine_charge);
            
            String lab_req;
            String lab_charge;
            String admit_req;
            String no_of_days;
            String room_charge;
            String nurse_charge;
            String operation_charge;
            if(jCheckBox1.isSelected())
            {
              lab_req="YES";
              lab_charge=jTextField2.getText();
              Double.parseDouble(lab_charge);
            }
            else
            {
              lab_req="NO";
              lab_charge="0";
              Double.parseDouble(lab_charge);
            }

            if(jCheckBox2.isSelected())
            {
              admit_req="YES";
              no_of_days=jTextField5.getText();
              Integer.parseInt(no_of_days);
              room_charge=jTextField6.getText(); 
              Double.parseDouble(room_charge);
              nurse_charge=jTextField4.getText();
              Double.parseDouble(nurse_charge);
              operation_charge=jTextField7.getText();
              Double.parseDouble(operation_charge);

            }
            else
            {
              admit_req="NO";
              no_of_days="0";
              Integer.parseInt(no_of_days);
              room_charge="0"; 
              Double.parseDouble(room_charge);
              nurse_charge="0";
              Double.parseDouble(nurse_charge);
              operation_charge="0";
              Double.parseDouble(operation_charge);

            }
            
            //String total_bill=jTextField8.getText();
            //Double.parseDouble(total_bill);
            //double fine=totals;
            try {
            Connection con = connectionprovider.getcon();
            Statement st = con.createStatement();
            st.executeUpdate("insert into bill values('" + p_id + "','" +bill_no + "','" + p_type + "','" + doc_charge + "','" + medicine_charge + "','" + lab_req+ "','" + lab_charge + "','"+ admit_req +"','"+ no_of_days +"','"+ room_charge +"','"+ nurse_charge +"','"+ operation_charge +"','"+ totals +"')");
            JOptionPane.showMessageDialog(null, "Successfully Updated");
            //setVisible(false);
            //new billingcounter().setVisible(true);
            jTextArea1.setText("****************  VISHWARAJ HOSPITAL  ***************\n");
            jTextArea1.setText(jTextArea1.getText()+"*****************    Patient Bill  Card    ********************\n");
            jTextArea1.setText(jTextArea1.getText()+"*********************************************************\n");
            java.util.Date obj = new java.util.Date();
            String date2 = obj.toString();
           jTextArea1.setText(jTextArea1.getText()+"\nCurrent Date-: "+date2+"\n\n");   
           //jTextArea1.setText(jTextArea1.getText()+"LAB DATE-: "+date+"\n\n");   
           jTextArea1.setText(jTextArea1.getText()+"Patient ID.-:"+p_id+" \t\tBill Number.-:"+bill_no+"\n\n");
           jTextArea1.setText(jTextArea1.getText()+"********************Patient Type -:"+p_type+"********************\n\n   ");
           jTextArea1.setText(jTextArea1.getText()+"Doctor Charge -:\t"+doc_charge+" rs /-\n");
           jTextArea1.setText(jTextArea1.getText()+"Medicine Charge -:\t"+medicine_charge+" rs /-\n");
           jTextArea1.setText(jTextArea1.getText()+"LAB Report  -:\t"+lab_req+"\n");
           jTextArea1.setText(jTextArea1.getText()+"LAB Charge -: \t "+lab_charge+" rs /-\n");
           jTextArea1.setText(jTextArea1.getText()+"Admit ? -: \t\t"+admit_req+"\n");
           jTextArea1.setText(jTextArea1.getText()+"No.of Days in Hospital -:\t"+no_of_days+"\n");
           jTextArea1.setText(jTextArea1.getText()+"Room Charge -:\t"+room_charge+" rs /-\n");
           jTextArea1.setText(jTextArea1.getText()+"Nursing Charge -:\t"+nurse_charge+" rs /-\n");
           jTextArea1.setText(jTextArea1.getText()+"Operation Charge -:\t"+operation_charge+" rs /-\n\n");
           jTextArea1.setText(jTextArea1.getText()+"*********************************************************\n");
           jTextArea1.setText(jTextArea1.getText()+"Total Charge  -:\t"+totals+" rs /-\n");
           jTextArea1.setText(jTextArea1.getText()+"                                                                       Signiture ");
           
            }
            catch (SQLException e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Data enter is incorrect");
            }
            
        }
        
        
        else  
            JOptionPane.showMessageDialog(null,"PatientID Field is EMPTY !");
                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            boolean print = jTextArea1.print();
        } catch (Exception e) {
            
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            String doc_charge=jTextField10.getText();
            double d=  Double.parseDouble(doc_charge);
            String medicine_charge=jTextField3.getText();
            double m= Double.parseDouble(medicine_charge);
            String lab_req;
            String lab_charge;
            String admit_req;
            String no_of_days;
            String room_charge;
            String nurse_charge;
            String operation_charge;  
            
                      
            if(jCheckBox1.isSelected())
            {
              lab_req="YES";
              lab_charge=jTextField2.getText();
              double l=Double.parseDouble(lab_charge);
              labss = l;
             
            }
            else
            {
              lab_req="NO";
              lab_charge="0";
              double l=Double.parseDouble(lab_charge);
              labss = l;
            }

            if(jCheckBox2.isSelected())
            {
              admit_req="YES";
              no_of_days=jTextField5.getText();
              int No=Integer.parseInt(no_of_days);
              room_charge=jTextField6.getText(); 
              double roomc=Double.parseDouble(room_charge);
              nurse_charge=jTextField4.getText();
              double nurse=Double.parseDouble(nurse_charge);
              operation_charge=jTextField7.getText();
              double op=Double.parseDouble(operation_charge);
              ad = roomc + nurse + op ;

            }
            else
            {
              admit_req="NO";
              no_of_days="0";
              Integer.parseInt(no_of_days);
              room_charge="0"; 
              Double.parseDouble(room_charge);
              nurse_charge="0";
              Double.parseDouble(nurse_charge);
              operation_charge="0";
              Double.parseDouble(operation_charge);
              double roomc=Double.parseDouble(room_charge);
               double nurse=Double.parseDouble(nurse_charge);
               double op=Double.parseDouble(operation_charge);
               ad = roomc + nurse + op ;
              
              

            }
            totals= d + m + labss + ad ;
            String aa = String.format("%.2f",totals);
            jTextField8.setText(aa);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "EMPTY !!!");
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        // jTextArea1.setText("*****************\n");
        setVisible(false);
        new billingcounter().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billingcounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billingcounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billingcounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billingcounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billingcounter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
